chef/mixlib-log

lib/mixlib/log.rb, spec/mixlib/log_spec.rb
Ruby does not have a destructor concept so the opened files should be closed explicitly. 
The Ruby Logger which is used as a default logger here does not close log devices it opened until #close method is called. When #rest! happens the logger instance gets destroyed but the #close method
is not triggered.
This patch should help to solve the problem described here: https://github.com/chef/chef/issues/3435
=> File log devices opened by mixlib-log should be closed.

.travis.yml, features/steps/log.rb, lib/mixlib/log/formatter.rb
This is a maintenance PR.
- Travis: Rubies matching ruby-build versions
- RSpec: Avoid deprecated `should`
- Rubygems update past 2.6.10, to be able to install Rainbow
- Rubocop: Pass lint
=> Travis: update Ruby versions, pass lint

mixlib-log.gemspec, spec/mixlib/log/formatter_spec.rb, spec/mixlib/log_spec.rb, spec/spec_helper.rb
This PR upgrades RSpec in the gemspec to 3.7 and disables the monkey-patching needed to support bare "describe".
=> RSpec: use 3.7, disable monkey patching mode

.travis.yml, lib/mixlib/log.rb, lib/mixlib/log/child.rb, lib/mixlib/log/formatter.rb, lib/mixlib/log/logger.rb, lib/mixlib/log/logging.rb, spec/mixlib/log/child_spec.rb, spec/mixlib/log/formatter_spec.rb, spec/mixlib/log_spec.rb
We do two things here:
- create child loggers. This means we can create a new logger for a subsystem such as ohai, give it new metadata, but still only manage one set of logging outputs.
- attach a metadata hash to each message.
=> Structured Logging

lib/mixlib/log/logging.rb, spec/mixlib/log_spec.rb
This PR makes `logger.debug "Hello"` return `nil`.
Your existing code rescued and logged an exception using `warn`. The return value of that invocation was `nil`.
Someone comes along to upgrade that `warn` to use a configurable mixlib-log logger. The return value of that logged exception is now non-nil.
- Fixes #21
=> Logging methods (debug, info, warn, error, fatal) all return nil

lib/mixlib/log.rb, lib/mixlib/log/child.rb, spec/mixlib/log_spec.rb
Signed-off-by: Thom May <thom@chef.io>
=> enable metadata to be got and set

Rakefile, mixlib-log.gemspec
=> Remove the changelog generator gem

.rubocop.yml, .travis.yml, Gemfile, README.md, Rakefile, lib/mixlib/log/version.rb, mixlib-log.gemspec
Also sync our travis config with our other gems
=> Test on all the Ruby versions we support

lib/mixlib/log.rb
This PR edits a YARD documentation annotation.
With the whitespace, YARD no longer thinks "at-sign logger" is a directive to YARD
None.
=> Add whitespace, to avoid YARD warning

lib/mixlib/log.rb
In #49, I made a change to avoid a warning. Now, I took a second look at the output, and it rendered wrong.
This PR uses the YARD escape notation, to avoid a warning AND to avoid the whitespace rendering as a monospace-formatted section.
None.
=> Escape YARD annotation to avoid directive

.expeditor/config.yml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md, .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md, .github/PULL_REQUEST_TEMPLATE.md, .github/lock.yml, .travis.yml, CONTRIBUTING.md, appveyor.yml
Add a contributing.md file
Update codeowners for the new teams
Add new github templates
Test on all the ruby versions in appveyor
Add issue locking
Fix expeditor for the new issue labels
=> Expand testing / Update GitHub templates

lib/mixlib/log.rb, lib/mixlib/log/logger.rb, spec/mixlib/log_spec.rb
This removes all warnings emitted during testing of mixlib-log or inspec.
`ruby -w`, `rspec -w`, and `minitest -w` all run with `$-w = true` and output warnings on use of uninitialized variables among other things. This PR cleans those up for this project. It also changes some tests around to be more idiomatic and to avoid logging going to stdout on top of the rspec output.
- [o] I have updated the documentation accordingly.
- [o] I have added tests to cover my changes.
=> Resolve all warnings emitted during testing

lib/mixlib/log.rb, lib/mixlib/log/child.rb, lib/mixlib/log/logger.rb
require_relative is significantly faster and should be used when available.
=> Substitute require for require_relative

Gemfile, lib/mixlib/log.rb, mixlib-log.gemspec, spec/mixlib/log/formatter_spec.rb, spec/spec_helper.rb
A few new chefstyle rules to improve readability here.
=> Replace __FILE__ with __dir__ and other minor chefstyle fixes

.expeditor/verify.pipeline.yml, Gemfile, mixlib-log.gemspec
2.7 is EOL and 3.0 is near EOL, but bumping this up to 2.7 to eliminate 2.5 and 2.6
=> Bump minimum to 2.7

lib/mixlib/log/logger.rb
Upcoming ruby3.3 will have enhanced Logger class:
https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1 which initializes newly added instance variables.
Without initializing such variables (in super class), now using subclass of Logger will cause exception.
To avoid this, first call super, then execute additional subclass initialization.
Fixes #73.
=> Support ruby3.3 Logger by properly initialize super class

mixlib-log.gemspec
`ffi` 1.17 requires ruby 3.1 or greater, so restrict to `< 1.17.0`
=> ffi less than 1.17.0 because of ruby 3.0

lib/mixlib/log/logger.rb, spec/mixlib/log/logger_spec.rb
https://github.com/chef/mixlib-log/pull/74 fixed an issue with Ruby 3.3's version of Logger. However, it dropped `Mixlib::Log::Formatter` from the formatter, so all messages now output as a Hash instead of a string.
=> Fix formatter regression from Ruby 3.3 Logger fix

.expeditor/verify.pipeline.yml, mixlib-log.gemspec
This is required for Ruby 3.3, but works on 3.1+
Limiting FFI to 1.17.0 because of https://github.com/ffi/ffi/issues/1139
=> Move ffi dependency forward

mixlib-log.gemspec
https://github.com/chef/mixlib-log/pull/81 limited the ffi version to <= 1.17.0, but it's not actually broken as explained in https://github.com/ffi/ffi/issues/1139#issuecomment-2632381142.
The issues Chef are having are specific to precompiled native Gems on Omnibus Chef builds.
=> Relax ffi dependency to allow 1.17.1 and up
